# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DoctorsPoint' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DoctorsPoint
pod 'Firebase/Core'
pod 'FirebaseDatabase' #database
pod 'Firebase/Auth'
pod "ViewAnimator"
pod 'BulletinBoard'
pod "CollectionKit"
pod "CollectionKit/WobbleAnimator"


pod 'Fabric', '~> 1.9.0'
pod 'Crashlytics', '~> 3.12.0'

  target 'DoctorsPointTests' do
    inherit! :search_paths
    # Pods for testing
  end
	
  target 'DoctorsPointUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end



#https://youtu.be/cubXeDj0LPI
#https://www.youtube.com/watch?v=FgCIRMz_3dE
#https://stackoverflow.com/questions/45598916/how-to-have-user-log-in-and-registration-on-same-page-using-django
#https://www.youtube.com/watch?v=qy7qC2a5_9g
#https://www.youtube.com/watch?v=pbRfxfRQu4U
#https://medium.com/@ashikabala01/how-to-build-login-and-sign-up-functionality-for-your-ios-app-using-firebase-within-15-mins-df4731faf2f7
#http://nipponcolors.com/#usu
#https://visme.co/blog/website-color-schemes/
#https://console.firebase.google.com/project/doctor-s-point-f62c1/overview
#https://firebase.google.com/docs/ios/setup?authuser=0
#https://www.youtube.com/watch?v=ZHPmDeu4Rr0
#https://github.com/TheKaseys/FirebaseAuthenticationSwift/tree/master
#https://stackoverflow.com/questions/26064315/hide-password-with-in-a-textfield
#https://stackoverflow.com/questions/11351689/detect-if-firebase-connection-is-lost-regained
#https://stackoverflow.com/questions/46205563/swift-proper-firebase-error-handling
#https://stackoverflow.com/questions/28074679/how-to-set-image-in-circle-in-swift
#https://stackoverflow.com/questions/24231680/loading-downloading-image-from-url-on-swift#
#https://stackoverflow.com/questions/24040519/error-showing-a-uialertview-in-swift
#https://stackoverflow.com/questions/25471114/how-to-validate-an-e-mail-address-in-swift
#https://stackoverflow.com/questions/12853795/showing-datepicker-18-years-back-and-lock-the-ui-datepicker-in-ios#
#https://stackoverflow.com/questions/43924323/how-to-display-the-name-of-the-day-of-the-week-from-date-in-swift#
#https://stackoverflow.com/questions/50916243/load-filter-data-from-firebase-and-show-specific-data
#https://stackoverflow.com/questions/3064864/uidatepicker-setting-maximum-and-minimum-dates-based-on-todays-date
#https://stackoverflow.com/questions/13169602/is-there-any-way-to-remove-the-year-of-the-date-picker
#https://stackoverflow.com/questions/37976468/saving-and-retrieving-date-in-firebase
#https://stackoverflow.com/questions/50709330/cycle-inside-building-could-produce-unreliable-results-xcode-10-error
#https://stackoverflow.com/questions/44559014/how-to-hide-days-in-uidatepicker
#https://stackoverflow.com/questions/45126049/firebase-retrieve-all-child-keys-and-child-values-into-separate-arrays-in-swif
#https://stackoverflow.com/questions/38481769/swift-perform-segue-after-googlesignin
#https://github.com/marcosgriselli/ViewAnimator
#https://github.com/alexaubry/BulletinBoard
#https://github.com/SoySauceLab/CollectionKit?utm_source=mybridge&utm_medium=blog&utm_campaign=read_more
#https://www.youtube.com/watch?v=ZHPmDeu4Rr0
#https://www.youtube.com/results?search_query=firebase+auth+error+swift
#https://www.youtube.com/watch?v=D8bBmnDQ7ZA
#https://www.youtube.com/watch?v=aa-lNWUVY7g
#https://store.rebeloper.com/courses/youtube-channel-resources/44763-uicollectionviewcontroller-programatically-with-collectionkit-in-xcode-10-swift-4-2-and-ios12/129545-collectionkit-pro
#https://www.youtube.com/watch?v=D5igmOH5zqQ&list=PL_csAAO9PQ8afuCeRDplLiuJbDshH2Z23&index=5
#https://www.youtube.com/watch?v=f4UErY-epYY&feature=youtu.be
#https://www.youtube.com/watch?v=2-nxXXQyVuE
#https://www.youtube.com/watch?v=gnRPR_v3BGc&list=PL_csAAO9PQ8afuCeRDplLiuJbDshH2Z23
#https://www.youtube.com/watch?v=UPKCULKi0-A
#https://www.youtube.com/watch?v=rDKtMz_PcLQ#
#https://www.youtube.com/watch?v=euf9c--areU
#https://www.youtube.com/watch?v=3MljDikYaG4
#https://www.youtube.com/watch?v=tYtBX6efJkc
#https://www.youtube.com/watch?v=YqpdgJ24R7E
#https://www.youtube.com/watch?v=a3S8i87Xo5Y
#https://www.youtube.com/watch?v=f4UErY-epYY&feature=youtu.be
#https://www.youtube.com/channel/UCK88iDIf2V6w68WvC-k7jcg
#
#
#
#
#
#
#
#
#



