# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DoctorsPoint' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DoctorsPoint
pod 'Firebase/Core'
pod 'FirebaseDatabase' #database
pod 'Firebase/Auth'
pod 'GoogleSignIn'

pod 'DateTimePicker'

  target 'DoctorsPointTests' do
    inherit! :search_paths
    # Pods for testing
  end
	
  target 'DoctorsPointUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
